# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-02 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('patronym', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Notarius',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('patronym', models.CharField(max_length=30)),
                ('certificate_num', models.CharField(max_length=30)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notary_registry.Activity_Type')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notary_registry.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='Notary_Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('building', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='phone',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notary_registry.Place'),
        ),
        migrations.AddField(
            model_name='notary_office',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notary_registry.Place'),
        ),
        migrations.AddField(
            model_name='notarius',
            name='notary_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notary_registry.Notary_Office'),
        ),
        migrations.AddField(
            model_name='notarius',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notary_registry.Place'),
        ),
        migrations.AddField(
            model_name='admin',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notary_registry.Place'),
        ),
    ]
