# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-02 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notary_registry', '0002_auto_20160602_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='type',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='activity_type',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
