# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-03 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notary_registry', '0003_auto_20160602_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(default='1111', max_length=256),
        ),
        migrations.AddField(
            model_name='admin',
            name='username',
            field=models.CharField(default='root', max_length=30),
        ),
    ]
