# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-03 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notary_registry', '0006_auto_20160603_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notarius',
            name='notary_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notary_registry.Notary_Office'),
        ),
    ]
