# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notary_registry', '0008_auto_20160606_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_type',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='admin',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='admin',
            name='patronym',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='admin',
            name='surname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(default='root', max_length=100),
        ),
        migrations.AlterField(
            model_name='notarius',
            name='certificate_num',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='notarius',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='notarius',
            name='patronym',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='notarius',
            name='surname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='notary_office',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='phone',
            name='type',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='building',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='street',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
